PENDING = "pending"
CONFIRMED = "confirmed"
CANCELLED = "cancelled"
COMPLETED = "completed"

ACTIVE_SLOT_STATUSES = (PENDING, CONFIRMED)
REPORTABLE_BOOKING_STATUSES = (PENDING, CONFIRMED, COMPLETED)
